import type { InferGetStaticPropsType, NextPage } from "next";
import Head from "next/head";
import { GetStaticProps } from "next";

export const getStaticProps: GetStaticProps = async (ctx) => {
  const data = await fetch(
    `${process.env.NEXT_PUBLIC_API_BASE_URI}/data.json`
  ).then((res) => res.json());

  return {
    props: { data },
  };
};

const Home: NextPage<InferGetStaticPropsType<typeof getStaticProps>> = ({
  data,
}) => {
  return (
    <div>
      <Head>
        <title>CalCaster 🧉</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <p>{JSON.stringify(data)}</p>
      </main>
    </div>
  );
};

export default Home;
